<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Stock Movement - {{ $period['from'] }}</title>
    <style>
        @page { margin: 1cm; }
        body { font-family: 'Helvetica', sans-serif; color: #333; line-height: 1.5; }
        
        /* Corporate Header */
        .company-header { border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 30px; }
        .report-title { font-size: 24px; font-weight: bold; text-transform: uppercase; margin: 0; }
        .meta { font-size: 10px; color: #666; font-family: monospace; }

        /* Statistics Grid */
        .stats-grid { width: 100%; margin-bottom: 30px; }
        .stats-cell { width: 33.33%; padding: 15px; border: 1px solid #eee; background: #fafafa; text-align: center; }
        .stats-label { font-size: 9px; text-transform: uppercase; color: #999; margin-bottom: 5px; }
        .stats-value { font-size: 18px; font-weight: bold; }

        /* Table Design */
        table { width: 100%; border-collapse: collapse; }
        th { background: #000; color: #fff; text-transform: uppercase; font-size: 10px; padding: 10px; text-align: left; }
        td { padding: 10px; font-size: 11px; border-bottom: 1px solid #eee; }
        
        .in { color: #16a34a; font-weight: bold; }
        .out { color: #dc2626; font-weight: bold; }
        
        .footer { margin-top: 50px; font-size: 10px; }
        .signature-line { border-top: 1px solid #000; width: 200px; margin-top: 40px; }
    </style>
</head>
<body>
    <div class="company-header">
        <table style="border:none;">
            <tr>
                <td style="border:none; padding:0;">
                    <h1 class="report-title">Stock Movement Report</h1>
                    <div class="meta">PERIOD_RANGE: {{ $period['from'] }} TO {{ $period['to'] }}</div>
                </td>
                <td style="border:none; padding:0; text-align:right;">
                    <div class="meta">GENERATED_ON: {{ now()->format('Y-m-d H:i') }}</div>
                    <div class="meta">SYSTEM_ID: URBANLINK_INV_V1</div>
                </td>
            </tr>
        </table>
    </div>

    <table class="stats-grid">
        <tr>
            <td class="stats-cell">
                <div class="stats-label">TOTAL_INBOUND</div>
                <div class="stats-value in">+{{ $summary['total_in'] }}</div>
            </td>
            <td class="stats-cell">
                <div class="stats-label">TOTAL_OUTBOUND</div>
                <div class="stats-value out">-{{ $summary['total_out'] }}</div>
            </td>
            <td class="stats-cell" style="background: #000; color: #fff;">
                <div class="stats-label" style="color: #666;">NET_VARIANCE</div>
                <div class="stats-value">{{ $summary['net_change'] }}</div>
            </td>
        </tr>
    </table>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Product / SKU</th>
                <th>Movement Type</th>
                <th style="text-align: right;">Change</th>
            </tr>
        </thead>
        <tbody>
            @forelse($transactions as $t)
            <tr>
                <td style="font-family: monospace;">{{ $t->transaction_date }}</td>
                <td>
                    <strong>{{ $t->product->name }}</strong><br>
                    <small style="color:#888;">{{ $t->product->sku }}</small>
                </td>
                <td>{{ $t->type }}</td> <td style="text-align: right;" class="{{ $t->quantity_change > 0 ? 'in' : 'out' }}">
                    {{ $t->quantity_change > 0 ? '+' : '' }}{{ $t->quantity_change }}
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="4" style="text-align: center; padding: 40px; color: #999;">
                    No transactions recorded for this period.
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>This report is an official record of inventory movement generated by UrbanLink IMS.</p>
        <div style="float: left;">
            <div class="signature-line"></div>
            <p>Warehouse Manager Signature</p>
        </div>
        <div style="float: right;">
            <div class="signature-line"></div>
            <p>System Auditor Signature</p>
        </div>
    </div>
</body>
</html>